#genome:    # you can give any name, it is not used by the script
#    db:                     '.+genome.+'    # optional regex to restrict to a specific blast database
#    '(scaffold\w+)':         '<a href="http://tripal/{id}">{id}</a> <a href="http://jbrowse?loc={id}">JBrowse</a>'    # key is a regex to match seq ids, value is a full html block, or simply an http url
#    '(superscaffold\w+)':    'http://tripal/{id}'
#protein:
#    db:                     '.+protein.+'
#    '*':                    'http://tripal/{id}'
#other:
#    '*':                    'http://google/{id}'
