_scheduler:
    resource: "@GenouestSchedulerBundle/Controller/SchedulerController.php"
    type: annotation

_blast:
    resource: "@GenouestBlastBundle/Controller/BlastController.php"
    type: annotation
